[versions]
protobufJava    = "4.33.0"
log4j           = "2.20.0"
junit-jupiter   = "5.9.3"
junit-platform  = "1.9.3"
tomcat          = "11.0.12"
guava           = "33.5.0-jre"
hazelcast       = "5.5.0"
jedis           = "5.2.0"
jca             = "2.4.7"
core-pva        = "5.0.2"
jython          = "2.7.3"
parquet         = "1.17.0"
hadoop          = "3.3.6"
httpclient      = "4.5.14"
httpcore        = "4.4.16"
commons-codec   = "1.15"
commons-io      = "2.14.0"
commons-lang3   = "3.18.0"
commons-math3   = "3.6.1"
commons-validator = "1.7"
commons-fileupload = "2.0.0-M3"
json-simple     = "1.1.1"
json            = "20250517"
opencsv         = "5.7.1"
mariadb         = "3.3.3"
jedis-nioredis  = "0.0.1"
jdbm            = "2.4"
disruptor       = "3.4.4"
awaitility      = "4.2.0"
commons-compress = "1.26.0"
commons-cli     = "1.5.0"
jinjava         = "2.8.1"
mockito         = "5.21.0"
jakarta-validation = "3.1.1"
svg-viewer      = "v1.2.1"
spotless-plugin = "8.1.0"
git-version-plugin = "3.0.0"
analyze-plugin  = "1.9.2"
protobuf-plugin = "0.9.5"

[libraries]
guava                    = { module = "com.google.guava:guava", version.ref = "guava" }
protobuf-java            = { module = "com.google.protobuf:protobuf-java", version.ref = "protobufJava" }
jca                      = { module = "org.epics:jca", version.ref = "jca" }
core-pva                 = { module = "org.phoebus:core-pva", version.ref = "core-pva" }
hazelcast                = { module = "com.hazelcast:hazelcast", version.ref = "hazelcast" }
jedis                    = { module = "redis.clients:jedis", version.ref = "jedis" }
jython                   = { module = "org.python:jython-standalone", version.ref = "jython" }
jakarta-validation       = { module = "jakarta.validation:jakarta.validation-api", version.ref = "jakarta-validation" }
log4j-api                = { module = "org.apache.logging.log4j:log4j-api", version.ref = "log4j" }
log4j-core               = { module = "org.apache.logging.log4j:log4j-core", version.ref = "log4j" }
log4j-slf4j2             = { module = "org.apache.logging.log4j:log4j-slf4j2-impl", version.ref = "log4j" }
log4j-jul                = { module = "org.apache.logging.log4j:log4j-jul", version.ref = "log4j" }
log4j-one-two-api    = { module = "org.apache.logging.log4j:log4j-1.2-api", version.ref = "log4j" }
disruptor                = { module = "com.lmax:disruptor", version.ref = "disruptor" }
commons-codec            = { module = "commons-codec:commons-codec", version.ref = "commons-codec" }
commons-io               = { module = "commons-io:commons-io", version.ref = "commons-io" }
commons-lang3            = { module = "org.apache.commons:commons-lang3", version.ref = "commons-lang3" }
commons-math3            = { module = "org.apache.commons:commons-math3", version.ref = "commons-math3" }
commons-validator        = { module = "commons-validator:commons-validator", version.ref = "commons-validator" }
commons-fileupload2-jakarta = { module = "org.apache.commons:commons-fileupload2-jakarta-servlet6", version.ref = "commons-fileupload" }
commons-fileupload2-core = { module = "org.apache.commons:commons-fileupload2-core", version.ref = "commons-fileupload" }
httpclient               = { module = "org.apache.httpcomponents:httpclient", version.ref = "httpclient" }
httpcore                 = { module = "org.apache.httpcomponents:httpcore", version.ref = "httpcore" }
jdbm                     = { module = "jdbm:jdbm", version.ref = "jdbm" }
json-simple              = { module = "com.googlecode.json-simple:json-simple", version.ref = "json-simple" }
json                     = { module = "org.json:json", version.ref = "json" }
opencsv                  = { module = "com.opencsv:opencsv", version.ref = "opencsv" }
mariadb                  = { module = "org.mariadb.jdbc:mariadb-java-client", version.ref = "mariadb" }
parquet-protobuf         = { module = "org.apache.parquet:parquet-protobuf", version.ref = "parquet" }
parquet-column           = { module = "org.apache.parquet:parquet-column", version.ref = "parquet" }
parquet-common           = { module = "org.apache.parquet:parquet-common", version.ref = "parquet" }
parquet-hadoop           = { module = "org.apache.parquet:parquet-hadoop", version.ref = "parquet" }
hadoop-common            = { module = "org.apache.hadoop:hadoop-common", version.ref = "hadoop" }
hadoop-client            = { module = "org.apache.hadoop:hadoop-client-api", version.ref = "hadoop" }
tomcat-servlet-api       = { module = "org.apache.tomcat:tomcat-servlet-api", version.ref = "tomcat" }
junit-jupiter-api        = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit-jupiter" }
junit-jupiter-params     = { module = "org.junit.jupiter:junit-jupiter-params", version.ref = "junit-jupiter" }
junit-jupiter-engine     = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit-jupiter" }
junit-platform-launcher  = { module = "org.junit.platform:junit-platform-launcher", version.ref = "junit-platform" }
awaitility               = { module = "org.awaitility:awaitility", version.ref = "awaitility" }
commons-compress         = { module = "org.apache.commons:commons-compress", version.ref = "commons-compress" }
commons-cli              = { module = "commons-cli:commons-cli", version.ref = "commons-cli" }
jinjava                  = { module = "com.hubspot.jinjava:jinjava", version.ref = "jinjava" }
mockito                  = { module = "org.mockito:mockito-core", version.ref = "mockito" }

[bundles]
parquet      = ["parquet-protobuf", "parquet-column", "parquet-common", "parquet-hadoop"]
log4j-impl   = ["log4j-slf4j2", "log4j-jul"]
log4j-runtime = ["log4j-core", "log4j-one-two-api", "disruptor"]
junit-impl   = ["junit-jupiter-api", "junit-jupiter-params"]
commons-shared = ["commons-codec", "commons-io", "commons-lang3", "commons-math3", "commons-validator"]

[plugins]
spotless     = { id = "com.diffplug.spotless", version.ref = "spotless-plugin" }
git-version  = { id = "com.palantir.git-version", version.ref = "git-version-plugin" }
analyze      = { id = "ca.cutterslade.analyze", version.ref = "analyze-plugin" }
protobuf     = { id = "com.google.protobuf", version.ref = "protobuf-plugin" }